full_rebuild: true
name: Photon Book Creator
author: CÃ©dric Soulas
url: https://cedricss.github.io/photon-book-creator
repository: https://github.com/cedricss/photon-book-creator
branch: gh-pages
version: 1.0
encoding: utf-8
themes:
    # General themes available: minimal, freelancer
    general: minimal
    # Code block themes available: monokai, github, vs
    code: monokai
defaults:
  -
    values:
      layout: "index"
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
